# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run 
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: 0509
    # The type of runner that the job will run on the
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Go to folder
        run: cd bin/
        

      - run: pwd
      - run: ls
      
      # Runs a single command using the runners shell
      - run: cd bin && chmod 777 * &&./TDClient.sh -o 1 -m master.xml -d "./../SQLs/" -pl yes
        env:
          TD_BASEURL: ${{secrets.TD_BASEURL }}
          TD_LOGDIRECTORY: .
          TD_PASSWORD: ${{secrets.TD_PASSWORD }}
          TD_USERNAME: ${{secrets.TD_USERNAME }}
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: ./liquibaseLogs*
